### ISSUE TITLE
Player Error 404

### ISSUE THREAD

**Issue by mrdeadlocked** [VenomCodeDev/ASA.StatImplant#1]
Getting an error 404 on player name
![image](https://github.com/VenomCodeDev/ASA.StatImplant/assets/461352/da0e1880-79fe-4228-a0fe-a6447d898f85)

**Comment by VenomCodeDev** [comment]
Can confirm this one. I saw it earlier but haven't gotten a chance to fix it yet. Thanks for submitting this either way, though! Hopefully, a fix will come by tomorrow.

**Comment by mrdeadlocked** [comment]
No worries! Mod will be a fun addition. Just hoping to help improve things.

**Comment by VenomCodeDev** [comment]
Issue appears to be resolved with [Version 10](https://legacy.curseforge.com/ark-survival-ascended/mods/stat-implant/files/4834017). Just open your game and/or restart your dedicated server and ARK Ascended should automatically update to the latest version available.
Thanks for reporting the bug!
